source 'https://rubygems.org'
gem 'sinatra'
gem 'awesome_print'
gem 'sidekiq'
gem 'json', '~> 1.8.6'
gem 'byebug'
gem 'foreman'
gem 'rerun'
gem 'pg'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'puma'
